#!/bin/sh

# disabled by default, remove following line to enable.
exit 0

if [ -n "$EX4DEBUG" ]; then
  echo "now debugging $0 $@"
  set -x
fi

[ -x /usr/lib/exim4/exim4 ] || exit 0

[ -f /etc/default/exim4 ] && . /etc/default/exim4

# Flush exim queue
/usr/sbin/exim4 -qqf
